on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-slim
    steps:
      - id: test 
        run: echo 'test={"a":1}' >> $GITHUB_OUTPUT
      - run: |
          echo ${{ fromJSON(steps.test.outputs.test).a }}
